[package]
name = "coretrace-ui"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
floem = "0.2.0"
coretrace-ipc = { path = "../ipc" }
tree-sitter = "0.26.12"
tree-sitter-c = "0.24.2"
tree-sitter-cpp = "0.23.4"
tree-sitter-cmake = "0.7.4"
tree-sitter-rust = "0.24.2"
tree-sitter-python = "0.25.0"
tree-sitter-json = "0.24.8"
tree-sitter-toml-ng = "0.7.0"
tree-sitter-md = "0.5.3"
tree-sitter-javascript = "0.25.0"
tree-sitter-bash = "0.25.1"
tree-sitter-yaml = "0.7.2"
rfd = "0.17.2"
coretrace-core = { version = "0.1.0", path = "../core" }
coretrace-extensions = { version = "0.1.0", path = "../extensions" }
coretrace-ctrace = { version = "0.1.0", path = "../ctrace" }
coretrace-lsp = { version = "0.1.0", path = "../lsp" }
coretrace-llm = { version = "0.1.0", path = "../llm" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
crossbeam-channel = "0.5"
