/**
 * @fileoverview IPC handlers for secure assistant configuration storage
 *
 * Uses Electron's safeStorage API to encrypt/decrypt the API key at rest.
 * Non-sensitive fields (provider, model, systemPrompt, …) are stored as
 * plain JSON alongside an encrypted blob for the key so that only the OS
 * credential store can read it back.
 *
 * The decrypted key never leaves the main process: the renderer only learns
 * whether a key is stored (`hasApiKey`), and provider requests read the key
 * through {@link loadStoredApiKey}.
 *
 * Storage location: <userData>/assistant-config.json
 *
 * @author CTrace GUI Team
 * @version 1.0.0
 */

const { ipcMain, safeStorage, app } = require('electron');
const fs = require('fs').promises;
const path = require('path');
const { trustFile } = require('../utils/workspaceTrust');

/** Conversation ids are generated by the renderer, so they are validated here before touching the filesystem. */
const CONVERSATION_ID_RE = /^[A-Za-z0-9_-]{1,64}$/;

/**
 * Return the path where the assistant config is persisted.
 * @returns {string}
 */
function getConfigPath() {
  return path.join(app.getPath('userData'), 'assistant-config.json');
}

function getConversationsDir() {
  return path.join(app.getPath('userData'), 'assistant-conversations');
}

/**
 * Read the stored config as written on disk (encrypted key blob included).
 * @returns {Promise<Object|null>} null when no config exists
 */
async function readStoredConfig() {
  try {
    return JSON.parse(await fs.readFile(getConfigPath(), 'utf8'));
  } catch (error) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
}

/**
 * Decrypt and return the stored API key, or null when none is stored.
 * @returns {Promise<string|null>}
 */
async function loadStoredApiKey() {
  const stored = await readStoredConfig();
  if (!stored || !stored._encryptedApiKey) return null;
  if (!safeStorage.isEncryptionAvailable()) return null;
  return safeStorage.decryptString(Buffer.from(stored._encryptedApiKey, 'base64'));
}

/**
 * Strip secret material and report whether a key exists.
 * @param {Object} stored
 * @returns {Object}
 */
function toRendererConfig(stored) {
  const { _encryptedApiKey, apiKey, ...rest } = stored;
  return { ...rest, hasApiKey: Boolean(_encryptedApiKey) };
}

/**
 * Resolve the conversation file for an id, rejecting anything that is not a
 * plain identifier (path separators, dots, empty strings, …).
 * @param {*} id
 * @returns {string|null}
 */
function conversationPath(id) {
  if (typeof id !== 'string' || !CONVERSATION_ID_RE.test(id)) return null;
  return path.join(getConversationsDir(), `${id}.json`);
}

const INVALID_CONVERSATION_ID = { success: false, error: 'Invalid conversation id' };

/**
 * Register IPC handlers for secure config operations.
 *
 * Channels exposed:
 *  - assistant-config-save   (invoke) – persist config, encrypting the apiKey
 *  - assistant-config-load   (invoke) – load config without the apiKey
 *  - assistant-config-clear  (invoke) – delete stored config
 */
function setupSecureStorageHandlers() {
  /**
   * Persist assistant configuration.
   * A non-empty `apiKey` replaces the stored key (encrypted); an empty one
   * keeps whatever key is already on disk. The plaintext key is never written.
   */
  ipcMain.handle('assistant-config-save', async (_event, config) => {
    try {
      const { apiKey, hasApiKey, _encryptedApiKey, ...toStore } = config || {};
      const existing = await readStoredConfig();

      if (apiKey) {
        if (!safeStorage.isEncryptionAvailable()) {
          return { success: false, error: 'OS credential encryption is unavailable; the API key was not saved' };
        }
        toStore._encryptedApiKey = safeStorage.encryptString(apiKey).toString('base64');
      } else if (existing && existing._encryptedApiKey) {
        toStore._encryptedApiKey = existing._encryptedApiKey;
      }

      if (toStore.localModelPath) trustFile(toStore.localModelPath);

      await fs.writeFile(getConfigPath(), JSON.stringify(toStore, null, 2), 'utf8');
      console.log('[SecureStorage] Assistant config saved');
      return { success: true };
    } catch (error) {
      console.error('[SecureStorage] Error saving config:', error);
      return { success: false, error: error.message };
    }
  });

  /**
   * Load assistant configuration for the renderer (no secret material).
   */
  ipcMain.handle('assistant-config-load', async () => {
    try {
      const stored = await readStoredConfig();
      if (!stored) return { success: false, error: 'No config found' };
      if (stored.localModelPath) trustFile(stored.localModelPath);
      return { success: true, config: toRendererConfig(stored) };
    } catch (error) {
      console.error('[SecureStorage] Error loading config:', error);
      return { success: false, error: error.message };
    }
  });

  /**
   * Delete the stored assistant configuration.
   */
  ipcMain.handle('assistant-config-clear', async () => {
    try {
      await fs.unlink(getConfigPath());
      console.log('[SecureStorage] Assistant config cleared');
      return { success: true };
    } catch (error) {
      if (error.code === 'ENOENT') return { success: true };
      console.error('[SecureStorage] Error clearing config:', error);
      return { success: false, error: error.message };
    }
  });

  // ── Conversation history persistence ──────────────────────────────────────

  /**
   * Save (create or overwrite) a conversation.
   * Data: { id, title, history, createdAt }
   */
  ipcMain.handle('assistant-conversations-save', async (_event, data) => {
    const filePath = conversationPath(data && data.id);
    if (!filePath) return INVALID_CONVERSATION_ID;
    try {
      await fs.mkdir(getConversationsDir(), { recursive: true });
      await fs.writeFile(filePath, JSON.stringify({ ...data, updatedAt: new Date().toISOString() }, null, 2), 'utf8');
      return { success: true };
    } catch (error) {
      console.error('[SecureStorage] Error saving conversation:', error);
      return { success: false, error: error.message };
    }
  });

  /**
   * List all saved conversations, sorted newest first.
   * Returns: { success, conversations: [{ id, title, createdAt, updatedAt }] }
   */
  ipcMain.handle('assistant-conversations-list', async () => {
    try {
      const dir = getConversationsDir();
      let files;
      try {
        files = await fs.readdir(dir);
      } catch (e) {
        if (e.code === 'ENOENT') return { success: true, conversations: [] };
        throw e;
      }
      const conversations = [];
      for (const f of files) {
        if (!f.endsWith('.json')) continue;
        try {
          const raw = await fs.readFile(path.join(dir, f), 'utf8');
          const { id, title, createdAt, updatedAt } = JSON.parse(raw);
          conversations.push({ id, title, createdAt, updatedAt });
        } catch (_) { /* skip corrupt files */ }
      }
      conversations.sort((a, b) => new Date(b.updatedAt || b.createdAt) - new Date(a.updatedAt || a.createdAt));
      return { success: true, conversations };
    } catch (error) {
      console.error('[SecureStorage] Error listing conversations:', error);
      return { success: false, error: error.message };
    }
  });

  /**
   * Load a single saved conversation by id.
   * Returns: { success, conversation: { id, title, history, createdAt, updatedAt } }
   */
  ipcMain.handle('assistant-conversations-load', async (_event, id) => {
    const filePath = conversationPath(id);
    if (!filePath) return INVALID_CONVERSATION_ID;
    try {
      const raw = await fs.readFile(filePath, 'utf8');
      return { success: true, conversation: JSON.parse(raw) };
    } catch (error) {
      console.error('[SecureStorage] Error loading conversation:', error);
      return { success: false, error: error.message };
    }
  });

  /**
   * Delete a saved conversation by id.
   */
  ipcMain.handle('assistant-conversations-delete', async (_event, id) => {
    const filePath = conversationPath(id);
    if (!filePath) return INVALID_CONVERSATION_ID;
    try {
      await fs.unlink(filePath);
      return { success: true };
    } catch (error) {
      if (error.code === 'ENOENT') return { success: true };
      console.error('[SecureStorage] Error deleting conversation:', error);
      return { success: false, error: error.message };
    }
  });
}

module.exports = { setupSecureStorageHandlers, loadStoredApiKey };
